- name: Ansible not able to remove umanaged files automatically need to do it manualy
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"
  loop_control:
    label: "{{ item.path }}"
