- name: Enable forwarding
  action: copy src=roles/forwarding/files/etc/rc.conf.d/forwarding
    dest=/etc/rc.conf.d/forwarding owner=root group=wheel mode=0664
  tags: forwarding
  when: "'dut' in group_names"
