- name: loop_benches calling bench
  vars:
     benches:
       - 1
       - 2
       - 3
       - 4
       - 5
  include_role:
    name: bench
  loop: "{{ benches }}"
  loop_control:
    loop_var: bench
