- name: /etc/rc.conf.d/interface-tx
  template: src=roles/interfaces/files/etc/rc.conf.d/interface-tx.j2
    dest=/etc/rc.conf.d/interface-tx owner=root group=wheel mode=0644
  when: "'generators' in group_names or 'dut' in group_names"

- name: /etc/rc.conf.d/interface-rx
  template: src=roles/interfaces/files/etc/rc.conf.d/interface-rx.j2
    dest=/etc/rc.conf.d/interface-rx owner=root group=wheel mode=0644
  when: "'receivers' in group_names or 'dut' in group_names"
