- name: Generate etc/rc.conf.d/management file
  template: src=roles/management/files/etc/rc.conf.d/management.j2
    dest=/etc/rc.conf.d/management owner=root group=wheel mode=0644
    #validate='bird -pc %s'
  tags: management
  #notify:
  #    - restart bird
