- name: Copy host systctl tuning file
  action: copy src={{ inventory_hostname }}/etc/sysctl.conf
    dest=/etc/sysctl.conf owner=root group=wheel mode=0664
  tags: tuning
  when: "'dut' in group_names"
