- name: start pkg-receiver
  debug:
    msg: start pkg-receiver on {{ inventory_hostname }}
  when: "'receivers' in group_names"
- name: bench
  debug:
    msg: firmware {{ firmware }}, config {{ config }}, pktgen {{ pktgen }}, bench id {{ bench }}
  when: "'dut' in group_names"
- name: start pkg-generator
  debug:
    msg: start pkg-generator on {{ inventory_hostname }}
  when: "'generators' in group_names"
