---
# This playbook start a bench.

# Apply common configuration to all hosts (admin should already be configured)
# So useless part
# List of hosts in group are dynamic:
# They depends of the DUT to be benched and familiy (VPN benches need endpoints)
# TO DO:
# - move management, interfaces and save_cfg (last) into hosts all
# - move all the rest into a 'config' loop dedicated to dut
# - Remove non-managed files (/etc/rc.conf, all no-more used /etc/rc.conf.d/)

# config_lab (pkt gen and receive)
# loop 1: firmware_dut (loop_var: for_each_firmware)
# loop 1.1: config_dut (loop_var: for_each_configs)
# loop 1.1.1: pkt setup (loop_var: for_each_pktgen)
# loop 1.1.1.1: bench (loop_var: for_each_bench)
- hosts: all
  roles:
  - register_files_to_delete
  - delete_previous_files
  - management
  - interfaces
  - forwarding
  - static_routes
  - static_arp
  - tuning_rc
  - tuning_sysctl
  - save_cfg
