- name: /etc/rc.conf.d/static_arp
  template:
    src: roles/static_arp/files/etc/rc.conf.d/static_arp.j2
    dest: /etc/rc.conf.d/static_arp
    owner: root
    group: wheel
    mode: 0644
  tags: static_arp
  when: "'dut' in group_names"
