- name: /etc/rc.conf.d/static_routes
  template:
    src: roles/static_routes/files/etc/rc.conf.d/static_routes.j2
    dest: /etc/rc.conf.d/static_routes
    owner: root
    group: wheel
    mode: 0644
  tags: static_routes
  when: "'dut' in group_names"
